package workouts;

import material.Colors;
import general.BackButtonActivity;
import android.content.Intent;
import android.graphics.PorterDuff.Mode;
import android.graphics.drawable.Drawable;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import de.couchdev.trainingassistant.R;

/**
 * With this activity the user chooses whether to create a new workout from a list of exercises or to let it be
 * generated by choosing which parts of his body he want to train with the workout.
 * @author Tim Reimer
 *
 */
public class CreateWorkoutActivity extends BackButtonActivity {

	
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_createworkout);
        createBackButton();
        
        // apply theme color
        Button exercise = (Button) findViewById(R.id.fromExercisesButton);
        Drawable image = getResources().getDrawable(R.drawable.white_button_selector);
        image.setColorFilter(Colors.getThemeColor(), Mode.MULTIPLY);
        exercise.setBackground(image);
        Button effect = (Button) findViewById(R.id.fromEffectButton);
        Drawable image2 = getResources().getDrawable(R.drawable.white_button_selector);
        image2.setColorFilter(Colors.getThemeColor(), Mode.MULTIPLY);
        effect.setBackground(image2);
    }
    
    /**
     * Starts the activity to create a new workout from a list of exercises.
     * @param v The clicked view. Here a button.
     */
    public void fromExercises(View v){
		Intent intent = new Intent(this, ChooseExercisesActivity.class);
		startActivityForResult(intent, WorkoutsActivity.NEW_SET);
    }
    
    /**
     * Start the activity to create a new workout from the effect of it to his body.
     * @param v The clicked view. Here a button.
     */
    public void fromEffect(View v){
		Intent intent = new Intent(this, FromEffectActivity.class);
		startActivityForResult(intent, WorkoutsActivity.NEW_SET);
    }

	@Override
	protected void onActivityResult(int requestCode, int resultCode, Intent data) {
	    if (resultCode == RESULT_OK) {
	        if (requestCode == WorkoutsActivity.NEW_SET) {
				setResult(RESULT_OK, data);
				finish();
	        }
	    }
	}
}
